=== tiagomiotto/poo/Labs/java/Lab8/total.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT total (journalist,title,local,date,subtitle?,resume?,article)>
<!ATTLIST total
  xmlns CDATA #REQUIRED ''>

<!ELEMENT journalist (name)>
<!ATTLIST journalist
  xmlns CDATA #REQUIRED  ''>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #REQUIRED ''>

<!ELEMENT local (name)>
<!ATTLIST local
  xmlns CDATA #REQUIRED ''>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  xmlns CDATA #REQUIRED ''>

<!ELEMENT subtitle (#PCDATA)>
<!ATTLIST subtitle
  xmlns CDATA #IMPLIED ''>

<!ELEMENT resume (body)>
<!ATTLIST resume
  xmlns CDATA #IMPLIED ''>

<!ELEMENT article (body)>
<!ATTLIST article
  xmlns CDATA #REQUIRED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #REQUIRED ''>

<!ELEMENT body (#PCDATA)>
<!ATTLIST body
  xmlns CDATA #REQUIRED ''>

=== tiagomiotto/poo/Labs/java/Lab8/total.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE total SYSTEM "total.dtd">
<total>

<journalist>
    <name>Ola Nordmann</name>
</journalist>
<title>O dia</title>
<local>
 <name>Lisboa</name>
</local>
<date>21/02/2019</date>

<subtitle>Subtitle</subtitle>
<resume>
 <body>
	Resumo teste
 </body>
</resume>

<article>
 <body>
	Artigo de testes
 </body>
</article>


</total>
